app/accounts/urls.py
from accounts import views

from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('my-profile/', views.MyProfile.as_view(), name='my-profile'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.ActivateUser.as_view(), name='activate-user'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

]

app/api/urls.py
from django.urls import include, path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions


app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('v1/', include('api.v1.urls')),

]

app/currency/urls.py
from currency import views as currency_views

from django.urls import path

app_name = 'currency'

urlpatterns = [
    path('contactus/', currency_views.ContactusList.as_view(), name="contactus"),
    path('contactus/create/', currency_views.ContactusCreate.as_view(), name="contactus_create"),

    path('rate/list/', currency_views.RateList.as_view(), name="rate_list"),
    path('rate/create/', currency_views.RateCreate.as_view(), name="rate_create"),
    path('rate/detail/<int:pk>/', currency_views.RateDetail.as_view(), name="rate_detail"),
    path('rate/update/<int:pk>/', currency_views.RateUpdate.as_view(), name="rate_update"),
    path('rate/delete/<int:pk>/', currency_views.RateDelete.as_view(), name="rate_delete"),

    path('source/list/', currency_views.SourceList.as_view(), name="source_list"),
    path('source/create/', currency_views.SourceCreate.as_view(), name="source_create"),
    path('source/detail/<int:pk>/', currency_views.SourceDetail.as_view(), name="source_detail"),
    path('source/update/<int:pk>/', currency_views.SourceUpdate.as_view(), name="source_update"),
    path('source/delete/<int:pk>/', currency_views.SourceDelete.as_view(), name="source_delete"),

]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('check-email/', TemplateView.as_view(template_name='activation.html'), name='check-email'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('currency/', include('currency.urls')),

    path('api/', include('api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

app/currency/models.py
from datetime import datetime

from currency import model_choices as mch

from django.db import models
from django.templatetags.static import static


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=254)
    subject = models.CharField(max_length=200)
    message = models.TextField(max_length=1000)


class Source(models.Model):
    name = models.CharField(max_length=64, unique=True)
    code_name = models.PositiveSmallIntegerField(choices=mch.SourceCodeName.choices, unique=True)
    url = models.CharField(max_length=255)
    social = models.CharField(max_length=255, null=True, blank=True)
    logo = models.FileField(upload_to='bank_logo', default=None, null=True, blank=True)

    def __str__(self):
        return self.name

    def logo_url(self):
        if self.logo:
            return self.logo.url

        return static('img/bank-logo.png')


class Rate(models.Model):
    type = models.CharField(max_length=5, choices=mch.RateType.choices)  # noqa: VNE003, A003
    base_type = models.CharField(max_length=5, choices=mch.RateType.choices, default=mch.RateType.UAH)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)
    buy = models.DecimalField(max_digits=10, decimal_places=2)
    sale = models.DecimalField(max_digits=10, decimal_places=2)

app/currency/forms.py
from currency.models import ContactUs, Rate, Source

from django import forms


class ContactusForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('email_from', 'subject', 'message')


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ('name', 'code_name', 'url', 'social', 'logo')


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = ('type', 'base_type', 'source', 'buy', 'sale')

app/currency/views.py
from currency.filters import RateFilter
from currency.forms import ContactusForm, RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.tasks import sendmail_new_сontactus

from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http.request import QueryDict
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from django_filters.views import FilterView


# ContactUs
class ContactusList(ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus.html'


# ContactUs Create Form
class ContactusCreate(CreateView):
    model = ContactUs
    template_name = 'contactus_create.html'
    form_class = ContactusForm
    success_url = reverse_lazy('currency:contactus')

    def form_valid(self, form):
        response = super().form_valid(form)

        data = form.cleaned_data
        subject = f"Contact us: {data['subject']}"
        message_body = f'''
        Support Email

        From: {data['email_from']}
        Message: {data['message']}
        '''
        from_email = data['email_from']

        sendmail_new_сontactus.delay(subject, message_body, from_email)

        return response

    def form_invalid(self, form):
        return super().form_invalid(form)


# Source
class SourceList(ListView):
    queryset = Source.objects.all().order_by('-id')
    template_name = 'source_list.html'


# Source create
class SourceCreate(CreateView):
    model = Source
    template_name = 'source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


# Source update
class SourceUpdate(UpdateView):
    model = Source
    template_name = 'source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


# Source delete
class SourceDelete(DeleteView):
    model = Source
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source_list')


# Source detail
class SourceDetail(DetailView):
    model = Source
    template_name = 'source_detail.html'


# Rate
class RateList(FilterView):
    queryset = Rate.objects.all().order_by('-id').select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 5
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        parameters = QueryDict(mutable=True)

        for key, value in self.request.GET.items():
            if key != 'page' and value:
                parameters[key] = value
        context['filter_param'] = parameters.urlencode()
        return context


# Rate create
class RateCreate(CreateView):
    model = Rate
    template_name = 'rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


# Rate update
class RateUpdate(UserPassesTestMixin, UpdateView):
    model = Rate
    template_name = 'rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.success(self.request, 'No access for this operation. Only superuser')
        return redirect('/currency/rate/list')


# Rate delete
class RateDelete(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.success(self.request, 'No access for this operation. Only superuser')
        return redirect('/currency/rate/list')


# Rate detail
class RateDetail(DetailView):
    model = Rate
    template_name = 'rate_detail.html'

app/currency/templates/includes/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'index' %}" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="{% url 'currency:contactus' %}" class="nav-link px-2 text-muted">Contact list</a>
        </li>
        <li class="nav-item"><a href="{% url 'currency:rate_list' %}" class="nav-link px-2 text-muted">Rate</a></li>
        <li class="nav-item"><a href="{% url 'currency:source_list' %}" class="nav-link px-2 text-muted">Source</a></li>
        <li class="nav-item"><a href="{% url 'currency:contactus_create' %}" class="nav-link px-2 text-muted">Contact
            Us</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Hillel, Currency</p>
</footer>

app/currency/templates/includes/messages.html
{% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
{% endif %}

app/currency/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'currency:contactus' %}">Contact list</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'currency:rate_list' %}">Rate</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'currency:source_list' %}">Source</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'currency:contactus_create' %}">Contact Us</a>
                </li>
            </ul>
            <span class="ml-auto">
            {% if request.user.is_authenticated %}

                <img src="{{ request.user.avatar_url }}" width="30" height="30" class="rounded-circle">

                <a href="{% url 'accounts:my-profile' %}" class="btn btn-outline-dark">My Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-outline-dark">Logout</a>
            {% else %}
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-dark">Sign Up</a>
                <a href="{% url 'login' %}" class="btn btn-outline-dark">Login</a>
            {% endif %}
            </span>
        </div>
    </div>
</nav>

app/currency/templates/includes/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{filter_param}}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&laquo;</a>
        </li>
        {% endif %}

        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active">
            <span class="page-link">{{ i }}</span>
        </li>
        {% else %}

        {% if i|add:"-3" <= page_obj.number and page_obj.number <= i|add:"3" %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}&{{filter_param}}">{{ i }}</a>
        </li>

        {% elif i|divisibleby:"10" or i == page_obj.paginator.num_pages %}
        <li class="page-item">
            <span> ... </span>
        </li>
        <li class="page-item">

            <a class="page-link" href="?page={{ i }}&{{filter_param}}">{{ i }}</a></li>
        {% endif %}

        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{filter_param}}">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
        </li>
        {% endif %}

    </ul>
</nav>