app/api/urls.py
from django.urls import include, path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions


app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('v1/', include('api.v1.urls')),

]

app/currency/urls.py
from currency import views as currency_views

from django.urls import path

app_name = 'currency'

urlpatterns = [
    path('contactus/', currency_views.ContactusList.as_view(), name="contactus"),
    path('contactus/create/', currency_views.ContactusCreate.as_view(), name="contactus_create"),

    path('rate/list/', currency_views.RateList.as_view(), name="rate_list"),
    path('rate/create/', currency_views.RateCreate.as_view(), name="rate_create"),
    path('rate/detail/<int:pk>/', currency_views.RateDetail.as_view(), name="rate_detail"),
    path('rate/update/<int:pk>/', currency_views.RateUpdate.as_view(), name="rate_update"),
    path('rate/delete/<int:pk>/', currency_views.RateDelete.as_view(), name="rate_delete"),

    path('source/list/', currency_views.SourceList.as_view(), name="source_list"),
    path('source/create/', currency_views.SourceCreate.as_view(), name="source_create"),
    path('source/detail/<int:pk>/', currency_views.SourceDetail.as_view(), name="source_detail"),
    path('source/update/<int:pk>/', currency_views.SourceUpdate.as_view(), name="source_update"),
    path('source/delete/<int:pk>/', currency_views.SourceDelete.as_view(), name="source_delete"),

]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('check-email/', TemplateView.as_view(template_name='activation.html'), name='check-email'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('currency/', include('currency.urls')),

    path('api/', include('api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

app/currency/models.py
from datetime import datetime

from currency import model_choices as mch

from django.db import models
from django.templatetags.static import static


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=254)
    subject = models.CharField(max_length=200)
    message = models.TextField(max_length=1000)


class Source(models.Model):
    name = models.CharField(max_length=64, unique=True)
    code_name = models.PositiveSmallIntegerField(choices=mch.SourceCodeName.choices, unique=True)
    url = models.CharField(max_length=255)
    social = models.CharField(max_length=255, null=True, blank=True)
    logo = models.FileField(upload_to='bank_logo', default=None, null=True, blank=True)

    def __str__(self):
        return self.name

    def logo_url(self):
        if self.logo:
            return self.logo.url

        return static('img/bank-logo.png')


class Rate(models.Model):
    type = models.CharField(max_length=5, choices=mch.RateType.choices)  # noqa: VNE003, A003
    base_type = models.CharField(max_length=5, choices=mch.RateType.choices, default=mch.RateType.UAH)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now)
    buy = models.DecimalField(max_digits=10, decimal_places=2)
    sale = models.DecimalField(max_digits=10, decimal_places=2)

app/currency/forms.py
from currency.models import ContactUs, Rate, Source

from django import forms


class ContactusForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('email_from', 'subject', 'message')


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ('name', 'code_name', 'url', 'social', 'logo')


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = ('type', 'base_type', 'source', 'buy', 'sale')

app/currency/views.py
from currency.filters import RateFilter
from currency.forms import ContactusForm, RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.tasks import sendmail_new_сontactus

from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http.request import QueryDict
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from django_filters.views import FilterView


# ContactUs
class ContactusList(ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contactus.html'


# ContactUs Create Form
class ContactusCreate(CreateView):
    model = ContactUs
    template_name = 'contactus_create.html'
    form_class = ContactusForm
    success_url = reverse_lazy('currency:contactus')

    def form_valid(self, form):
        response = super().form_valid(form)

        data = form.cleaned_data
        subject = f"Contact us: {data['subject']}"
        message_body = f'''
        Support Email

        From: {data['email_from']}
        Message: {data['message']}
        '''
        from_email = data['email_from']

        sendmail_new_сontactus.delay(subject, message_body, from_email)

        return response

    def form_invalid(self, form):
        return super().form_invalid(form)


# Source
class SourceList(ListView):
    queryset = Source.objects.all().order_by('-id')
    template_name = 'source_list.html'


# Source create
class SourceCreate(CreateView):
    model = Source
    template_name = 'source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


# Source update
class SourceUpdate(UpdateView):
    model = Source
    template_name = 'source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


# Source delete
class SourceDelete(DeleteView):
    model = Source
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source_list')


# Source detail
class SourceDetail(DetailView):
    model = Source
    template_name = 'source_detail.html'


# Rate
class RateList(FilterView):
    queryset = Rate.objects.all().order_by('-id').select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 5
    filterset_class = RateFilter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        parameters = QueryDict(mutable=True)

        for key, value in self.request.GET.items():
            if key != 'page' and value:
                parameters[key] = value
        context['filter_param'] = parameters.urlencode()
        return context


# Rate create
class RateCreate(CreateView):
    model = Rate
    template_name = 'rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


# Rate update
class RateUpdate(UserPassesTestMixin, UpdateView):
    model = Rate
    template_name = 'rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.success(self.request, 'No access for this operation. Only superuser')
        return redirect('/currency/rate/list')


# Rate delete
class RateDelete(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.success(self.request, 'No access for this operation. Only superuser')
        return redirect('/currency/rate/list')


# Rate detail
class RateDetail(DetailView):
    model = Rate
    template_name = 'rate_detail.html'

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>

{% include 'includes/navbar.html' %}
{% include 'includes/messages.html' %}

<div class="container">
    {% block content %}
    {% endblock content %}
    {% include 'includes/footer.html' %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

app/currency/templates/contactus.html
{% extends 'base.html' %}
{% block title %}ContactUs List{% endblock %}

{% block content %}


<table class="table table-striped table-hover">
    <tr>
        <th scope="col">id</th>
        <th scope="col">email from</th>
        <th scope="col">subject</th>
        <th scope="col">message</th>
    </tr>
    {%for i in contactus_list %}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.email_from}}</td>
        <th scope="row">{{i.subject}}</th>
        <td>{{i.message}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

app/currency/templates/contactus_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Contact Us{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Send mail</button>
</form>



{% endblock content %}

app/currency/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>Home</h1>
<div>
    Welcome to Currency project
</div>

{% endblock content %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create source{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
<button type="submit" class="btn btn-primary">Create rate</button>


{% endblock content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}
{% block title %}Update source{% endblock %}
{% block content %}

<p>Do you want to delete 'Rate' with ID '{{ rate.id }}'</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>



{% endblock content %}

app/currency/templates/rate_detail.html
{% extends 'base.html' %}
{% block title %}Source detail{% endblock %}
{% block content %}

    <div>
        <p>Type - {{rate.type}}</p>
        <p>SOURCE - {{rate.source}}</p>
        <p>CREATED - {{rate.created}}</p>
        <p>BUY - {{rate.buy}}</p>
        <p>SALE - {{rate.sale}}</p>
    </div>

{% endblock content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}
{% block title %}Rate List{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <p>
        <form action="{% url 'currency:rate_create' %}">
            <button class="btn btn-secondary">Create rate</button>
        </form>
        </p>
    </div>
</div>
<div class="row">
    <div class="col">
        <form method="get">
            {{ filter.form.as_p }}
            <button type="submit" class="btn btn-primary">Apply</button>
        </form>
        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">type</th>
                <th scope="col">base type</th>
                <th scope="col">source</th>
                <th scope="col">buy</th>
                <th scope="col">sale</th>
                <th scope="col">created</th>
            </tr>
            {%for i in rate_list %}
            <tr>
                <td>{{i.type}}</td>
                <td>{{i.base_type}}</td>
                <td>{{i.source}}</td>
                <td>{{i.buy}}</td>
                <td>{{i.sale}}</td>
                <td>{{i.created| date:"d.m.Y H:i:s"}}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            Actions
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                            <li><a class="dropdown-item active"
                                   href="{% url 'currency:rate_detail' i.id %}">Detail</a></li>
                            <li><a class="dropdown-item" href="{% url 'currency:rate_update' i.id %}">Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'currency:rate_delete' i.id %}">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update rate{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Update rate</button>
</form>



{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create source{% endblock %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
<button type="submit" class="btn btn-primary">Create source</button>
</form>

{% endblock content %}

app/currency/templates/source_delete.html
{% extends 'base.html' %}
{% block title %}Update source{% endblock %}
{% block content %}

<p>Do you want to delete 'Source' with ID '{{ source.id }}'</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>



{% endblock content %}

app/currency/templates/source_detail.html
{% extends 'base.html' %}
{% block title %}Source detail{% endblock %}
{% block content %}

    <div>
        <div><img src="{{source.logo_url}}" width="100" height="100" class="rounded-circle"></div>
        <p>ID - {{source.id}}</p>
        <p>Name - {{source.name}}</p>
        <p>Code - {{source.code_name}}</p>
        <p>URL - {{source.url|default_if_none:""}}</p>
        <p>Social - {{source.social|default_if_none:""}}</p>
    </div>

{% endblock content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}
{% block title %}Source List{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <p>
        <form action="{% url 'currency:source_create' %}">
            <button class="btn btn-secondary">Create source</button>
        </form>
        </p>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-striped table-hover">
            <tr align="center">
                <th scope="col">logo</th>
                <th scope="col">name</th>
                <th scope="col">url</th>
                <th scope="col">social</th>
            </tr>
            {%for i in source_list %}
            <tr>
                <td><img src="{{i.logo_url}}" width="40" height="40" class="rounded-circle"></td>
                <th scope="row">{{i.name}}</th>
                <td>{{i.url}}</td>
                <td>{{i.social}}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            Actions
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                            <li><a class="dropdown-item active"
                                   href="{% url 'currency:source_detail' i.id %}">Detail</a></li>
                            <li><a class="dropdown-item" href="{% url 'currency:source_update' i.id %}">Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'currency:source_delete' i.id %}">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update source{% endblock %}
{% block content %}
<div><img src="{{source.logo_url}}" width="100" height="100" class="rounded-circle"></div>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
<button type="submit" class="btn btn-primary">Update source</button>
</form>

{% endblock content %}